language: node_js
node_js: lts/*

env:
  global:
    - ENCRYPTION_LABEL="9ea7ccbab3d2"

branches:
  only:
    - master

script:
  - shellcheck deploy.sh && npm run lint && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
